"""SCDR_RADR model factory."""
from utils.basicsr_compat import ensure_minimal_basicsr_compat


DEFAULT_SCDR_RADR_CONFIG = {
    "atd_img_size": 64,
    "atd_patch_size": 1,
    "atd_in_chans": 3,
    "atd_embed_dim": 192,
    "atd_depths": (6, 6, 6, 6, 6, 6),
    "atd_num_heads": (4, 4, 4, 4, 4, 4),
    "atd_window_size": 16,
    "atd_dim_ffn_td": 16,
    "atd_category_size": 192,
    "atd_num_tokens": 384,
    "atd_reducted_dim": 16,
    "atd_convffn_kernel_size": 5,
    "atd_mlp_ratio": 2.0,
    "atd_upscale": 4,
    "atd_img_range": 1.0,
    "atd_upsampler": "pixelshuffle",
    "atd_resi_connection": "1conv",
}

def _tuple_arg(value):
    if isinstance(value, (tuple, list)):
        return tuple(int(v) for v in value)
    if isinstance(value, str):
        return tuple(int(v.strip()) for v in value.split(",") if v.strip())
    return value


def get_model(
    use_radr=False,
    radr_layer_mode="last",
    radr_hidden_dim=32,
    radr_lambda=0.10,
    radr_tau=0.50,
    radr_init_bias=-4.0,
    radr_detach_feat=True,
    radr_use_correction=False,
    radr_corr_hidden_dim=64,
    radr_corr_lambda=0.05,
    radr_corr_scale=0.10,
    radr_corr_init_std=1e-4,
    radr_corr_detach_residual=True,
    radr_corr_gate_mode="ueff",
    radr_corr_feature_mode="shortcut_xatd",
    radr_corr_train_feature_modes="",
    use_radr_ccd=False,
    radr_ccd_upscale=4,
    radr_ccd_aux_init_std=1e-4,
    radr_ccd_aux_scale=0.10,
    radr_ccd_aux_use_gated_corr=True,
    use_radr_lch=False,
    radr_lch_hidden_dim=64,
    radr_lch_lambda=0.05,
    radr_lch_corr_scale=0.05,
    radr_lch_init_std=1e-4,
    radr_lch_gate_mode="u_eff",
    radr_lch_detach_map=True,
    use_scdr=False,
    scdr_alpha=0.49,
    scdr_return_routes=False,
    scdr_detach_routes=False,
    use_scdr_adapter=False,
    scdr_adapter_hidden_dim=32,
    scdr_adapter_scale=0.05,
    scdr_adapter_init_std=1e-5,
    **kwargs,
):
    # Build SCDR_RADR from CLI kwargs while preserving internal checkpoint-compatible keys.
    ensure_minimal_basicsr_compat()
    from model_archs.SCDR_RADR_arch import SCDR_RADR

    depths = _tuple_arg(kwargs.get("atd_depths", DEFAULT_SCDR_RADR_CONFIG["atd_depths"]))
    num_heads = _tuple_arg(kwargs.get("atd_num_heads", DEFAULT_SCDR_RADR_CONFIG["atd_num_heads"]))

    return SCDR_RADR(
        img_size=kwargs.get("atd_img_size", DEFAULT_SCDR_RADR_CONFIG["atd_img_size"]),
        patch_size=kwargs.get("atd_patch_size", DEFAULT_SCDR_RADR_CONFIG["atd_patch_size"]),
        in_chans=kwargs.get("atd_in_chans", DEFAULT_SCDR_RADR_CONFIG["atd_in_chans"]),
        embed_dim=kwargs.get("atd_embed_dim", DEFAULT_SCDR_RADR_CONFIG["atd_embed_dim"]),
        depths=depths,
        num_heads=num_heads,
        window_size=kwargs.get("atd_window_size", DEFAULT_SCDR_RADR_CONFIG["atd_window_size"]),
        dim_ffn_td=kwargs.get("atd_dim_ffn_td", DEFAULT_SCDR_RADR_CONFIG["atd_dim_ffn_td"]),
        category_size=kwargs.get("atd_category_size", DEFAULT_SCDR_RADR_CONFIG["atd_category_size"]),
        num_tokens=kwargs.get("atd_num_tokens", DEFAULT_SCDR_RADR_CONFIG["atd_num_tokens"]),
        reducted_dim=kwargs.get("atd_reducted_dim", DEFAULT_SCDR_RADR_CONFIG["atd_reducted_dim"]),
        convffn_kernel_size=kwargs.get("atd_convffn_kernel_size", DEFAULT_SCDR_RADR_CONFIG["atd_convffn_kernel_size"]),
        mlp_ratio=kwargs.get("atd_mlp_ratio", DEFAULT_SCDR_RADR_CONFIG["atd_mlp_ratio"]),
        qkv_bias=True,
        ape=False,
        patch_norm=True,
        use_checkpoint=kwargs.get("atd_use_checkpoint", False),
        upscale=kwargs.get("atd_upscale", DEFAULT_SCDR_RADR_CONFIG["atd_upscale"]),
        img_range=kwargs.get("atd_img_range", DEFAULT_SCDR_RADR_CONFIG["atd_img_range"]),
        upsampler=kwargs.get("atd_upsampler", DEFAULT_SCDR_RADR_CONFIG["atd_upsampler"]),
        resi_connection=kwargs.get("atd_resi_connection", DEFAULT_SCDR_RADR_CONFIG["atd_resi_connection"]),
        atd_use_dawa=kwargs.get("atd_use_dawa", False),
        atd_dawa_long=kwargs.get("atd_dawa_long", 32),
        atd_dawa_short=kwargs.get("atd_dawa_short", 8),
        atd_dawa_conf_threshold=kwargs.get("atd_dawa_conf_threshold", 0.15),
        atd_dawa_layer_mode=kwargs.get("atd_dawa_layer_mode", "last"),
        atd_use_gaa=kwargs.get("atd_use_gaa", False),
        atd_gaa_layer_mode=kwargs.get("atd_gaa_layer_mode", "last"),
        atd_gaa_num_geo=kwargs.get("atd_gaa_num_geo", 2),
        atd_gaa_max_offset=kwargs.get("atd_gaa_max_offset", 16),
        atd_gaa_block_size=kwargs.get("atd_gaa_block_size", 32),
        atd_gaa_estimator_source=kwargs.get("atd_gaa_estimator_source", "lr_gray"),
        atd_use_topk_retrieval=kwargs.get("atd_use_topk_retrieval", False),
        atd_topk=kwargs.get("atd_topk", 8),
        atd_topk_max_tokens=kwargs.get("atd_topk_max_tokens", 4096),
        atd_use_gdc=kwargs.get("atd_use_gdc", False),
        atd_geo_feat_dim=kwargs.get("atd_geo_feat_dim", 5),
        use_fdg=kwargs.get("use_fdg", False),
        fdg_df=kwargs.get("fdg_df", 16),
        fdg_lambda0=kwargs.get("fdg_lambda0", 1.0),
        fdg_init_alpha=kwargs.get("fdg_init_alpha", 0.01),
        fdg_in_channels=kwargs.get("fdg_in_channels", 5),
        fdg_layer_mode=kwargs.get("fdg_layer_mode", "last"),
        fdg_use_acmsa_route_bias=kwargs.get("fdg_use_acmsa_route_bias", True),
        fdg_route_bias_max=kwargs.get("fdg_route_bias_max", 1.0),
        fdg_route_bias_init=kwargs.get("fdg_route_bias_init", 0.0),
        fdg_route_bias_detach=kwargs.get("fdg_route_bias_detach", False),
        fdg_use_td_ste=kwargs.get("fdg_use_td_ste", False),
        fdg_use_gumbel_grouping=kwargs.get("fdg_use_gumbel_grouping", False),
        fdg_tau_gumbel=kwargs.get("fdg_tau_gumbel", 1.0),
        fdg_use_routeprob_bias=kwargs.get("fdg_use_routeprob_bias", False),
        use_struct_prior=kwargs.get("use_struct_prior", False),
        struct_prior_type=kwargs.get("struct_prior_type", "scdrc"),
        struct_scale_max=kwargs.get("struct_scale_max", 0.15),
        struct_delta_init=kwargs.get("struct_delta_init", 0.0),
        struct_last_weight_std=kwargs.get("struct_last_weight_std", 0.0),
        struct_use_residual_reliability=kwargs.get("struct_use_residual_reliability", False),
        struct_residual_detach=kwargs.get("struct_residual_detach", True),
        struct_rr_stats=kwargs.get("struct_rr_stats", "abs_mean,abs_std,ratio"),
        struct_prior_scope=kwargs.get("struct_prior_scope", "global"),
        struct_local_channels=kwargs.get("struct_local_channels", 16),
        struct_local_scale_max=kwargs.get("struct_local_scale_max", 0.05),
        struct_local_last_weight_std=kwargs.get("struct_local_last_weight_std", 0.003),
        struct_local_detach=kwargs.get("struct_local_detach", True),
        struct_layer_mode=kwargs.get("struct_layer_mode", "last"),
        struct_hidden_dim=kwargs.get("struct_hidden_dim", 64),
        use_decb=kwargs.get("use_decb", False),
        decb_num_tokens=kwargs.get("decb_num_tokens", 64),
        decb_gate_max=kwargs.get("decb_gate_max", 0.10),
        decb_gate_init=kwargs.get("decb_gate_init", -4.0),
        decb_token_init_std=kwargs.get("decb_token_init_std", 0.02),
        decb_proj_init_std=kwargs.get("decb_proj_init_std", 0.001),
        decb_layer_mode=kwargs.get("decb_layer_mode", "last"),
        decb_gate_condition=kwargs.get("decb_gate_condition", "shortcut"),
        decb_residual_detach=kwargs.get("decb_residual_detach", True),
        use_radr=use_radr,
        radr_layer_mode=radr_layer_mode,
        radr_hidden_dim=radr_hidden_dim,
        radr_lambda=radr_lambda,
        radr_tau=radr_tau,
        radr_init_bias=radr_init_bias,
        radr_detach_feat=radr_detach_feat,
        radr_use_correction=radr_use_correction,
        radr_corr_hidden_dim=radr_corr_hidden_dim,
        radr_corr_lambda=radr_corr_lambda,
        radr_corr_scale=radr_corr_scale,
        radr_corr_init_std=radr_corr_init_std,
        radr_corr_detach_residual=radr_corr_detach_residual,
        radr_corr_gate_mode=radr_corr_gate_mode,
        radr_corr_feature_mode=radr_corr_feature_mode,
        radr_corr_train_feature_modes=radr_corr_train_feature_modes,
        use_radr_ccd=use_radr_ccd,
        radr_ccd_upscale=radr_ccd_upscale,
        radr_ccd_aux_init_std=radr_ccd_aux_init_std,
        radr_ccd_aux_scale=radr_ccd_aux_scale,
        radr_ccd_aux_use_gated_corr=radr_ccd_aux_use_gated_corr,
        use_radr_lch=use_radr_lch,
        radr_lch_hidden_dim=radr_lch_hidden_dim,
        radr_lch_lambda=radr_lch_lambda,
        radr_lch_corr_scale=radr_lch_corr_scale,
        radr_lch_init_std=radr_lch_init_std,
        radr_lch_gate_mode=radr_lch_gate_mode,
        radr_lch_detach_map=radr_lch_detach_map,
        use_scdr=use_scdr,
        scdr_alpha=scdr_alpha,
        scdr_return_routes=scdr_return_routes,
        scdr_detach_routes=scdr_detach_routes,
        use_scdr_adapter=use_scdr_adapter,
        scdr_adapter_hidden_dim=scdr_adapter_hidden_dim,
        scdr_adapter_scale=scdr_adapter_scale,
        scdr_adapter_init_std=scdr_adapter_init_std,
    )
