"""Build supervised RADR labels from help maps or by recomputing help_map."""

import argparse
import os
import sys

import numpy as np
import torch
from PIL import Image

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if REPO_ROOT not in sys.path:
    sys.path.insert(0, REPO_ROOT)

from scripts.analyze_dict_residual_help import (  # noqa: E402
    autocast_context,
    build_baseline_model,
    discover_lr_images,
    ensure_same_hw,
    find_gt_for_lr,
    load_baseline_checkpoint,
    safe_vis_name,
    set_zero_dict_residual,
)
from utils.image_utils import load_rgb_tensor  # noqa: E402
from utils.scene_gate_utils import scene_and_rel_path, write_csv_rows  # noqa: E402


def parse_args():
    parser = argparse.ArgumentParser(description="Build RADR supervised labels from help maps")
    parser.add_argument("--help_map_dir", type=str, default="",
                        help="directory containing *_help.npy generated by analyze_dict_residual_help.py")
    parser.add_argument("--dataset_root", type=str, required=True,
                        help="dataset root with LR/ and GT/ subfolders")
    parser.add_argument("--dataset_name", type=str, required=True)
    parser.add_argument("--checkpoint", type=str, default="",
                        help="optional; if help_map_dir is empty, recompute help maps from checkpoint")
    parser.add_argument("--save_dir", type=str, required=True)
    parser.add_argument("--scale", type=int, default=4)
    parser.add_argument("--tau_neg", type=float, default=1e-4)
    parser.add_argument("--tau_pos", type=float, default=1e-4)
    parser.add_argument("--crop_border", type=int, default=None)
    parser.add_argument("--max_images", type=int, default=0)
    parser.add_argument("--device", type=str, default="cuda")
    parser.add_argument("--amp", type=int, default=1)
    return parser.parse_args()


def normalize_rel_path(path):
    return str(path).replace("\\", "/").strip("/")


def infer_full_help_map(help_arr, full_hw, crop_border, rel_path):
    """把裁边后的 help_map 恢复成与 GT 同尺寸的 full-size 图，并让边界无效。"""
    full_h, full_w = int(full_hw[0]), int(full_hw[1])
    help_arr = np.asarray(help_arr, dtype=np.float32)
    if help_arr.ndim != 2:
        raise RuntimeError("Expected 2D help_map for {}, got {}".format(rel_path, help_arr.shape))
    full = np.zeros((full_h, full_w), dtype=np.float32)
    region_valid = np.zeros((full_h, full_w), dtype=np.float32)
    if help_arr.shape == (full_h, full_w):
        full[...] = help_arr
        region_valid[...] = 1.0
        return full, region_valid
    border = int(crop_border)
    inner_h = full_h - 2 * border
    inner_w = full_w - 2 * border
    if inner_h <= 0 or inner_w <= 0:
        raise RuntimeError("Invalid crop_border {} for GT shape {} on {}".format(border, full_hw, rel_path))
    if help_arr.shape != (inner_h, inner_w):
        raise RuntimeError(
            "help_map shape mismatch for {}: help {} vs GT {} with crop_border {}".format(
                rel_path, help_arr.shape, full_hw, border
            )
        )
    full[border:border + inner_h, border:border + inner_w] = help_arr
    region_valid[border:border + inner_h, border:border + inner_w] = 1.0
    return full, region_valid


def build_label_from_help(help_full, region_valid, tau_neg, tau_pos):
    """根据 help_map 生成 unreliable label 和 valid mask。"""
    tau_ignore = max(abs(float(tau_neg)), abs(float(tau_pos)))
    unreliable = (help_full < -float(tau_neg)) & (region_valid > 0.5)
    reliable = (help_full > float(tau_pos)) & (region_valid > 0.5)
    ignore = (~unreliable) & (~reliable)
    if tau_ignore > 0.0:
        ignore = ((np.abs(help_full) <= tau_ignore) & (region_valid > 0.5)) | (region_valid <= 0.5)
    valid = (~ignore).astype(np.float32)
    u_gt = unreliable.astype(np.float32)
    return u_gt[None, ...], valid[None, ...]


def gt_hw_from_path(gt_path):
    with Image.open(gt_path) as img:
        w, h = img.size
    return h, w


def load_help_map_index(help_map_dir):
    mapping = {}
    for name in sorted(os.listdir(help_map_dir)):
        if not name.endswith("_help.npy"):
            continue
        key = name[:-len("_help.npy")]
        mapping[key] = os.path.join(help_map_dir, name)
    if not mapping:
        raise RuntimeError("No *_help.npy files found under {}".format(help_map_dir))
    return mapping


def recompute_help_map(model, lr, gt, device, amp_enabled, rel_path):
    with torch.no_grad():
        with autocast_context(device, amp_enabled):
            set_zero_dict_residual(model, False)
            sr_full = model(lr)
            set_zero_dict_residual(model, True)
            sr_nodict = model(lr)
            set_zero_dict_residual(model, False)
        sr_full = sr_full.detach().float().clamp(0.0, 1.0)
        sr_nodict = sr_nodict.detach().float().clamp(0.0, 1.0)
        gt = gt.detach().float().clamp(0.0, 1.0)
        ensure_same_hw(sr_full, gt, rel_path)
        ensure_same_hw(sr_nodict, gt, rel_path)
        err_full = torch.mean(torch.abs(sr_full - gt), dim=1, keepdim=True)
        err_nodict = torch.mean(torch.abs(sr_nodict - gt), dim=1, keepdim=True)
        help_map = (err_nodict - err_full).squeeze(0).squeeze(0).cpu().numpy().astype(np.float32)
    return help_map


def main():
    args = parse_args()
    lr_root = os.path.join(args.dataset_root, "LR")
    gt_root = os.path.join(args.dataset_root, "GT")
    if not os.path.isdir(lr_root) or not os.path.isdir(gt_root):
        raise FileNotFoundError("Expected LR/ and GT/ under {}".format(args.dataset_root))
    crop_border = int(args.scale if args.crop_border is None else args.crop_border)
    save_label_dir = os.path.join(args.save_dir, "labels")
    os.makedirs(save_label_dir, exist_ok=True)

    help_map_index = {}
    if args.help_map_dir:
        if not os.path.isdir(args.help_map_dir):
            raise FileNotFoundError("help_map_dir not found: {}".format(args.help_map_dir))
        help_map_index = load_help_map_index(args.help_map_dir)

    device = torch.device(args.device)
    amp_enabled = bool(int(args.amp))
    model = None
    if not help_map_index:
        if not args.checkpoint:
            raise ValueError("Either --help_map_dir or --checkpoint must be provided")
        model = build_baseline_model(args.scale)
        load_baseline_checkpoint(model, args.checkpoint)
        model = model.to(device)
        model.eval()

    lr_paths = discover_lr_images(lr_root)
    if args.max_images and args.max_images > 0:
        lr_paths = lr_paths[:int(args.max_images)]
    if not lr_paths:
        raise RuntimeError("No LR images found under {}".format(lr_root))

    rows = []
    unreliable_ratios = []
    reliable_ratios = []
    ignore_ratios = []
    for idx, lr_path in enumerate(lr_paths, start=1):
        gt_path = find_gt_for_lr(lr_path, lr_root, gt_root)
        if gt_path is None:
            raise FileNotFoundError("Unable to find GT pair for {}".format(lr_path))
        scene, rel_path = scene_and_rel_path(lr_path, lr_root, folder="")
        rel_path = normalize_rel_path(rel_path)
        safe_name = safe_vis_name(rel_path)
        full_hw = gt_hw_from_path(gt_path)

        if help_map_index:
            help_path = help_map_index.get(safe_name, None)
            if help_path is None:
                raise KeyError("Unable to match help map for image_rel_path {} (safe_name={})".format(rel_path, safe_name))
            help_arr = np.load(help_path)
        else:
            lr = load_rgb_tensor(lr_path).unsqueeze(0).to(device)
            gt = load_rgb_tensor(gt_path).unsqueeze(0).to(device)
            help_arr = recompute_help_map(model, lr, gt, device, amp_enabled, rel_path)

        help_full, region_valid = infer_full_help_map(help_arr, full_hw, crop_border, rel_path)
        u_gt, valid = build_label_from_help(help_full, region_valid, args.tau_neg, args.tau_pos)
        reliable = ((valid > 0.5) & (u_gt < 0.5)).astype(np.float32)
        num_pixels = int(u_gt.shape[-2] * u_gt.shape[-1])
        unreliable_ratio = float(u_gt.mean())
        reliable_ratio = float(reliable.mean())
        ignore_ratio = float(1.0 - valid.mean())

        label_path = os.path.abspath(os.path.join(save_label_dir, "{}_u_gt.npy".format(safe_name)))
        valid_path = os.path.abspath(os.path.join(save_label_dir, "{}_valid.npy".format(safe_name)))
        np.save(label_path, u_gt.astype(np.float32))
        np.save(valid_path, valid.astype(np.float32))

        rows.append({
            "dataset": args.dataset_name,
            "scene": scene,
            "image_rel_path": rel_path,
            "label_path": label_path,
            "valid_path": valid_path,
            "unreliable_ratio": "{:.6f}".format(unreliable_ratio),
            "reliable_ratio": "{:.6f}".format(reliable_ratio),
            "ignore_ratio": "{:.6f}".format(ignore_ratio),
            "num_pixels": num_pixels,
        })
        unreliable_ratios.append(unreliable_ratio)
        reliable_ratios.append(reliable_ratio)
        ignore_ratios.append(ignore_ratio)
        if idx % 50 == 0 or idx == len(lr_paths):
            print("Processed {}/{} images".format(idx, len(lr_paths)))

    index_csv = os.path.join(args.save_dir, "radr_label_index.csv")
    summary_csv = os.path.join(args.save_dir, "radr_label_summary.csv")
    write_csv_rows(
        index_csv,
        ["dataset", "scene", "image_rel_path", "label_path", "valid_path",
         "unreliable_ratio", "reliable_ratio", "ignore_ratio", "num_pixels"],
        rows,
        append=False,
    )
    write_csv_rows(
        summary_csv,
        ["dataset", "num_images", "tau_neg", "tau_pos",
         "unreliable_ratio_mean", "reliable_ratio_mean", "ignore_ratio_mean"],
        [{
            "dataset": args.dataset_name,
            "num_images": len(rows),
            "tau_neg": "{:.6g}".format(float(args.tau_neg)),
            "tau_pos": "{:.6g}".format(float(args.tau_pos)),
            "unreliable_ratio_mean": "{:.6f}".format(float(np.mean(unreliable_ratios)) if unreliable_ratios else 0.0),
            "reliable_ratio_mean": "{:.6f}".format(float(np.mean(reliable_ratios)) if reliable_ratios else 0.0),
            "ignore_ratio_mean": "{:.6f}".format(float(np.mean(ignore_ratios)) if ignore_ratios else 0.0),
        }],
        append=False,
    )
    print("Dataset: {}".format(args.dataset_name))
    print("Images: {}".format(len(rows)))
    print("Saved labels: {}".format(save_label_dir))
    print("Saved index CSV: {}".format(index_csv))
    print("Saved summary CSV: {}".format(summary_csv))


if __name__ == "__main__":
    main()
